### ISSUE TITLE
Command Prompt Working, Rich Presence Not.

### ISSUE THREAD

**Issue by ThunderAxolotl** [angelolz/CookieClickerRPC#33]
So The command prompt says it's working, but my discord doesn't have the rich presence.

**Comment by ThunderAxolotl** [comment]
Also my JDK file is under C:\Program Files\Java\jre-1.8\legal\jdk

**Comment by ThunderAxolotl** [comment]
Found out I was using JRE not JAVA, fixed it

**Comment by ThunderAxolotl** [comment]
![image](https://github.com/angelolz/CookieClickerRPC/assets/88669806/95df8a74-357a-4bc0-8d97-549346fe3007)
![image](https://github.com/angelolz/CookieClickerRPC/assets/88669806/671e1c40-d14e-4739-a334-d6e2f49213fd)

**Comment by angelolz** [comment]
Oops, there was a setup problem with URL forwarding on my domain. Please try again and let me know if the issue still happens. Thank you!

**Comment by ThunderAxolotl** [comment]
Ok it seems to have work the 2nd time I ran the command, but ill keep this open so u can look at that error.

**Comment by angelolz** [comment]
Hmm, yeah. That error comes from CCSE, which is one of the dependencies I use for my mod. If I'm not mistaken, I'm always pulling the latest version of CCSE when the mod is loaded, so if anything happens and it's CCSE-related, it's out of my control.

If any errors show up and your game freezes, usually reloading fixes that problem quickly. Although your game freezing shouldn't be a common issue.

Thank you for reporting all these errors! Will close as the problem is resolved, but if you encounter any errors, feel free to reopen or make a new issue. :)
